public with sharing class ItemDTO {
    public String sourcePoductId {get; set;}
    public String productId {get; set;}
    public String size {get; set;}
    public String color {get; set;}
    public String sku {get; set;}
    public String productName {get; set;}
    public Decimal quantity {get; set;}
    public String description {get; set;}
    public Decimal unitPrice {get; set;}
    public Decimal totalPrice {get; set;}
 
}